version: '3.8'

services:
  tenant-service:
    build: 
      context: ./tenant-service
      dockerfile: Dockerfile
    image: tenant-service:latest
    ports:
      - "8080:8080"
    env_file:
      - ./tenant-service/.env

  main-app:
    build: 
      context: .
      dockerfile: Dockerfile
    image: main-app:latest
    ports:
      - "3000:8080"
    environment:
      - TENANT_SERVICE_URL=http://tenant-service:8080
    depends_on:
      - tenant-service