version: '3.8'

services:
  tenant-service:
    build: 
      context: ./tenant-service
      dockerfile: Dockerfile
    image: tenant-service:latest
    ports:
      - "8080:8080"
    env_file:
      - ./tenant-service/.env
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 128M
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - app-network
    volumes:
      - tenant-service-data:/app/data

  main-app:
    build: 
      context: .
      dockerfile: Dockerfile
    image: main-app:latest
    ports:
      - "3000:8080"
    environment:
      - TENANT_SERVICE_URL=http://tenant-service:8080
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 128M
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    depends_on:
      tenant-service:
        condition: service_healthy
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  tenant-service-data: