apiVersion: v1
kind: Service
metadata:
  name: tenant-service
  namespace: tenant-service
spec:
  selector:
    app: tenant-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP 