[package]
name = "tenant-service"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7"
tokio = "1.40.0"    
serde = { version = "1.0", features = ["derive"] }
surrealdb = "2.2.1"
tower-http = { version = "0.5", features = ["cors"] }
dotenv = "0.15"
thiserror = "1.0.64"