apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-ssl-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-ssl-proxy
  template:
    metadata:
      labels:
        app: nginx-ssl-proxy
    spec:
      containers:
      - name: nginx
        image: openresty/openresty:1.21.4.1-alpine-fat
        ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 15
          periodSeconds: 20
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: lua-scripts
          mountPath: /etc/nginx/lua
        - name: ssl-data
          mountPath: /etc/nginx/ssl
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
      - name: lua-scripts
        configMap:
          name: lua-scripts
      - name: ssl-data
        persistentVolumeClaim:
          claimName: ssl-data 