apiVersion: v1
kind: Service
metadata:
  name: nginx-ssl-proxy
  namespace: ${k8s_namespace}
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    name: http
  - port: 443
    targetPort: 443
    name: https
  selector:
    app: nginx-ssl-proxy