apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tenant-service-dev

bases:
  - ../../base
  - ../../tenant-service/base
  - ../../nginx/base
  - ../../redis/base

patchesStrategicMerge:
  - tenant-service-replicas.yaml
  - nginx-replicas.yaml
  - redis-replicas.yaml

configMapGenerator:
  - name: tenant-service-config
    behavior: merge
    literals:
      - environment_type=development
      - log_level=debug 